version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_instance
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: musique
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo_express_console
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_instance
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD : admin123

  musique-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musique-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/musique?authSource=admin
      app.jwtSecret: VGhpcyBpcyBhIG5ldyBzZWN1cmUgSldUIHNlY3JldCBnZW5lcmF0ZWQgd2l0aCBhIGhpZ2ggZW50cm9weSBsZXZlbCBmb3IgYWRkaXRpb25hbCBzZWN1cml0eSBwbGVhc2UgdXNlIGZvciBhdXRoZW50aWNhdGlvbg
      app.jwtExpirationInMs: 3600000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
